use CMD for handler in docker custom runtim

diff --git a/lambda_custom_runtime_shell_docker/bootstrap b/lambda_custom_runtime_shell_docker/bootstrap
--- a/lambda_custom_runtime_shell_docker/bootstrap
+++ b/lambda_custom_runtime_shell_docker/bootstrap
@@ -56,8 +56,17 @@ send_error_to_invocation() {
     fi    
 }
 
+# Check if at least one argument is provided
+if [ $# -gt 0 ]; then
+    lambda_handler=$1
+    echo "Lambda Handler: $lambda_handler"
+else
+    echo "Error: No argument provided. Please specify a lambda handler."
+    exit 1
+fi
+
 # Initialization - load function handler using the function
-load_handler_function "$LAMBDA_TASK_ROOT" "$_HANDLER"
+load_handler_function "$LAMBDA_TASK_ROOT" "$lambda_handler"
 
 # Processing
 while true
@@ -72,7 +81,7 @@ do
     REQUEST_ID=$(extract_request_id "$HEADERS")
 
     # Run the handler function using the function
-    RESPONSE=$(run_handler "$_HANDLER" "$EVENT_DATA")
+    RESPONSE=$(run_handler "$lambda_handler" "$EVENT_DATA")
 
     # Log the RESPONSE
     echo "Handler response: $RESPONSE"
